language: R
sudo: required
warnings_are_errors: true

before_install:
  - sudo rm /etc/apt/sources.list.d/pgdg-source.list* 
  - sudo apt-get -q remove libpq5* libpq-dev* postgis* postgres* libgdal* gdal* libhdf5* libnetcdf* libhdf4*
  - sudo rm -Rf /var/lib/postgresql /etc/postgresql
  - sudo apt-get install aptitude -y
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
#- sudo aptitude install -q  libhdf5-dev libhdf5-7 libhdf5-serial-dev hdf5-tools libpng12-dev libjpeg-dev libgeos-dev libgd2-xpm-dev libfreetype6-dev libgdal1-dev libproj-dev 
  - sudo aptitude install -y gdal-bin 
  - sudo aptitude install -y libgdal1-dev 
   