language: R
sudo: required
warnings_are_errors: true

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update
  - sudo apt-get install gdal-bin libgdal1 libgdal1-dev netcdf-bin libproj-dev
  - sudo apt-get install bootstrap