language: r
sudo: required
warnings_are_errors: true

r: 
    - devel

branches:
  except:
    - example-data
    - gh-pages

apt_packages: 
    - gdal-bin
    - libgdal-dev
    - libxml2-dev
    - libproj-dev

r_github_packages:
    - r-lib/covr
    

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
