language: R
sudo: required
warnings_are_errors: true

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - ./travis-tool.sh install_aptget gdal-bin libgdal1 libgdal1-dev netcdf-bin libproj-dev
  - ./travis-tool.sh bootstrap