language: R
sudo: required
warnings_are_errors: true

before_install:
  - sudo rm /etc/apt/sources.list.d/pgdg-source.list* 
  - sudo apt-get -qq purge postgis* postgresql*
  - sudo rm -Rf /var/lib/postgresql /etc/postgresql
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install -q bison flex python-lxml libfribidi-dev swig cmake librsvg2-dev colordiff postgis postgresql-9.1-postgis-2.0-scripts libpq-dev libpng12-dev libjpeg-dev libgif-dev libgeos-dev libgd2-xpm-dev libfreetype6-dev libfcgi-dev libcurl4-gnutls-dev libcairo2-dev libgdal1-dev libproj-dev libxml2-dev python-dev php5-dev libexempi-dev lcov lftp
   