language: R
sudo: required
warnings_are_errors: true

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update
  - sudo apt-get install libgdal-dev netcdf-bin libproj-dev