language: R
sudo: required
warnings_are_errors: true

before_install:
  - export PGUSER=postgres
  - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
  - sudo apt-get -qq purge postgis* postgresql*
  - sudo apt-add-repository -y ppa:cartodb/postgresql-9.3
  - sudo apt-add-repository -y ppa:cartodb/gis
  - sudo rm -Rf /var/lib/postgresql /etc/postgresql
  - sudo apt-get update -qq
  - sudo apt-get install -q postgresql-9.3-postgis-2.1
  - sudo apt-get install -q postgresql-contrib-9.3
  - sudo apt-get install -q gdal-bin libgdal-dev
  - echo -e "local\tall\tall\ttrust\nhost\tall\tall\t127.0.0.1/32\ttrust\nhost\tall\tall\t::1/128\ttrust" |sudo tee /etc/postgresql/9.3/main/pg_hba.conf
  - sudo service postgresql restart

install:
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 # we need at least g++-4.7 for c++11 features
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -y ttf-wqy-microhei make libstdc++6 libstdc++-4.8-dev valgrind boost1.55 python-nose libicu-dev libproj-dev libcairo-dev python-cairo-dev libcairo-dev python-cairo-dev libpng-dev libjpeg-dev libtiff-dev libwebp-dev libz-dev libfreetype6-dev libxml2-dev libsqlite3-dev