language: R
sudo: required
warnings_are_errors: true

before_install:
  - sudo rm /etc/apt/sources.list.d/pgdg-source.list* 
  - sudo apt-get -qq purge postgis* postgresql*
  - sudo rm -Rf /var/lib/postgresql /etc/postgresql
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install -q gdal-bin libgdal-dev

#install:
# - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
# - sudo apt-get update -qq
# - sudo apt-get install -y libproj-dev l libtiff-dev 