language: R
sudo: required
warnings_are_errors: true

before_install:
  - sudo rm /etc/apt/sources.list.d/pgdg-source.list* 
  - sudo apt-get -qq remove libpq5* libpq-dev* postgis* postgres* libgdal* gdal*
  - sudo rm -Rf /var/lib/postgresql /etc/postgresql
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install -q  librsvg2-dev colordiff libpng12-dev libjpeg-dev libgif-dev gdal-bin libgeos-dev libgd2-xpm-dev libfreetype6-dev libgdal-dev libgdal1-dev libproj-dev 
   