language: R
sudo: required
warnings_are_errors: true

before_script:
  - sudo apt-get install aptitude -y
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo aptitude install -y gdal-bin 
  - sudo aptitude install -y libgdal1-dev 
  - sudo aptitude install -y libproj-dev
  - Rscript -e "install.packages('devtools', repos = 'http://cran.r-project.org/')"
  - Rscript -e "install.packages('rgdal', repos = 'http://cran.r-project.org/')"

   
